### ISSUE TITLE
Webhook support like in Civ6 PYC

### ISSUE THREAD

**Issue by ZeiP** [pydt/api#13]
It'd be awesome if PYDT had the same kind of webhook support than in Civ 6 – this way we could use the same notification script for both. I started working on this at the branches below, but unfortunately the lack of a test environment and my lack of Angular skills took the development to a halt for now – it'd be awesome if this were finished, though.

* https://github.com/ZeiP/api/tree/feature/webhook
* https://github.com/ZeiP/web/tree/feature/webhook

**Comment by mrosack** [comment]
Thanks, I'll try and clean it up this weekend.  The API side shouldn't use any angular stuff, the only reason angular is included in there is to satisfy the shared library, I need to figure out a way to seperate the angular and non-angular stuff in the shared library.

Is value1/value2/value3 a common format for webhooks or should we do something more descriptive like gameName, userName, round?

**Comment by ZeiP** [comment]
value1/value2/value3 is the scheme used by Civilization 6, which is why I was thinking it would make sense to use that – that way any webhooks would work with both. It might make sense to duplicate the information also to more sensibly named fields. I was also thinking that it might be good to add a field for specifying that the webhook was called by PYDT – for example service: PYDT or similar.

**Comment by mrosack** [comment]
Thanks again, just deployed support for this.  Changes:

- https://github.com/pydt/api/commit/99cde9ef9fe449404f7ed94f3ec12f6313201ab0
- https://github.com/pydt/web/commit/dd7d469cbbf46c2078cdc8fc6ae50df3409fce0e
