### ISSUE TITLE
Defeated email only going to other players, not player defeated

### ISSUE THREAD

**Issue by Valamas** [pydt/api#20]
I suspect the You have been defeated email is not sending to the player that was defeated. It is however going to all the other players. 

The game this happened in is
https://www.playyourdamnturn.com/game/d1b6c04e-af17-423a-b7b5-03eaa5c731f4

**Comment by mrosack** [comment]
I still don't know why this is happening, but I just got defeated from a game and didn't get an email so it's definitely real, hopefully this is the fix.

**Comment by Valamas** [comment]
i noticed you were defeated in the Red Death game. You got an email?

**Comment by mrosack** [comment]
Yeah, i did get one this time!  Hopefully it's all good now, and I do have better logging in the system now if we need to troubleshoot this in the future.
